### ISSUE TITLE
次に読む本を決める！

### ISSUE THREAD

**Issue by risacan** [ikejirirb/GrokkingAlgorithms#12]

**Comment by risacan** [comment]
* [パーフェクトRuby](https://www.amazon.co.jp/dp/4774189774/?tag=can00-22c)
* [エフェクティブRuby](https://www.amazon.co.jp/dp/4798139823/?tag=can00-22)
* [メタプログラミングRuby](https://www.amazon.co.jp/dp/4873117437/?tag=can00-22)
    * あとのほうがよさそう
* [プログラミングRuby](https://www.amazon.co.jp/dp/4274066428/?tag=can00-22)
    * ドキュメントみればいいかも

私はどれも読んでないけど @katorie さんはもう読んだのもありそう

**Comment by katorie** [comment]
エフェクティブは一度読んだけどもう一度読みたい…！
メタプロは途中で挫折している…！

**Comment by risacan** [comment]
エフェクティブRubyがよさそう！

**Comment by katorie** [comment]
エフェクティブよさそう！と思ったんだけど、テスト駆動開発も気になる！
テスト駆動開発 https://www.amazon.co.jp/dp/4274217884/ref=cm_sw_r_cp_api_PyA3zbNXBCC8G

**Comment by katorie** [comment]
プロRuby 🍒  の登場 👐
